# Site configuration
# 1. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# 2. Gem settings
paginate: 5 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: SS_Geosaber # jekyll-seo-tag > Owners twitter username
author: Sidney Goveia # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Geosaber # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/SS_Geosaber
    - https://www.facebook.com/SS.Geosaber
    - https://www.linkedin.com/company/geosaber
    - https://plus.google.com/+geosaber
    - https://github.com/geosaber

# 3. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: America/Sao_Paulo # Timezone for blog posts and alike

# 4. Collections
collections:
  posts:
    title: Blog # Needed for Siteleaf
    output: true
    description: (2007-2017) <https://geosaber.blogspot.com> # The post list page content
    feature_text: |
      
    feature_image: "https://github.com/geosaber/r4geo/raw/gh-pages/img/geosaber_capa.png"

# 5. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "" # Default image for sharing

# 6. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: pt-BR # Set the site language
title: "Geosaber" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "Portal de Geotecnologias Livres" # Site description and default description, also used in jekyll-seo-tag
url: "https://www.geosaber.com.br" # Site url, also used in jekyll-seo-tag
baseurl: "/"
repo: "https://github.com/geosaber/site"
email: "geosaber@gmail.com"
google_analytics: 'UA-25726356-1'
# avatarurl: "https://www.gravatar.com/avatar/6c0377abcf4da91cdd35dea4554b2a4c" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference

# 7. Site navigation
navigation_header:
  Início: /
  Cursos: /courses/
  Blog: /blog/
  Tutoriais: /tutorials/
  Histórico: /services/
  Contato: /contact/
  Busca: /search/

navigation_footer:
  Audoc.con Assessoria e Consultoria: http://audoc.com.br

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/SS_Geosaber
  LinkedIn: https://www.linkedin.com/company/geosaber
  Google+: https://plus.google.com/+GeosaberBrasil
  Facebook: https://www.facebook.com/Sidney.Geosaber
  GitHub: https://github.com/geosaber
  link: https://www.geosaber.com.br
  RSS: /feed.xml

sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
  Twitter: "#1DA1F2"
  Facebook: "#3B5998"
  LinkedIn: "#0077B5"
  Email: "#1DA1F2"
